[build]
  command = "npm run build && rm -rf .next/cache"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "GEMINI_API_KEY_1,GEMINI_API_KEY_2"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**"

[[plugins]]
  package = "@netlify/plugin-nextjs"
